name: money_manage
description: "A new Flutter project."
publish_to: 'none' # Không xuất bản lên pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  http: ^1.1.0
  intl: ^0.19.0
  fl_chart: ^1.1.1
  shared_preferences: ^2.2.2
  expandable: ^5.0.1
  http_parser: ^4.0.0
  dio: ^5.9.0
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.5
  uuid: ^3.0.7
  path: ^1.9.0
  sqflite: ^2.3.0
  home_widget: ^0.8.1

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "icons/logo_savings.png"


flutter:
  uses-material-design: true
  assets:
    - icons/logo_savings.png
